### PR TITLE
Fix #59: sirepo compat test

### LINKED ISSUE #59: Unit tests for sirepo silas compatability

### PR DESCRIPTION
**Pull request by gurhar1133**
Tests elements and pulse to see if they are compatable with sirepo silas master branch

### CODE REVIEW

**Comment by gurhar1133** [comment]
Looks like only test failing is the compatibility test

**Review by bruhwiler — COMMENTED** [review]
One test is failing for me,
tests/pulse_test.py::test_sirepo_compatability FAILED

It looks like this branch was created prior to the most recent PR, merged yesterday.

The signature for the Drift and other classes has changed, so there will likely be some problems when this PR is merged.

**Comment by gurhar1133** [comment]
> One test is failing for me, tests/pulse_test.py::test_sirepo_compatability FAILED
> 
> It looks like this branch was created prior to the most recent PR, merged yesterday.
> 
> The signature for the Drift and other classes has changed, so there will likely be some problems when this PR is merged.

That is the test that checks compatibility with what is on sirepo master. The references `Drift` `Lens` etc are what sirepo master will generate. So the test failure indicates that what is on rlsaser rn will break sirepo. Which is the case (working on fixing it currently). So it's good that that test is failing. Sorry if I didn't specify in PR

**Comment by gurhar1133** [comment]
sirepo [PR](https://github.com/radiasoft/sirepo/pull/5963) where I fixed to reflect new rslaser API

**Comment by gurhar1133** [comment]
OK, fixes were merged in sirepo, so I am updating the test to reflect sirepo master

**Comment by gurhar1133** [comment]
@bruhwiler test is passing, showing that sirepo master is consistent with latest rslaser

**Review by bruhwiler — APPROVED** [review]
The new tests look good to me.
I see that the element propagators reflect the latest version of main

Tests are passing in my environment.

**Pull request merged**
